#!/usr/bin/env python3
"""Build lib/core/l10n/translations_en.dart from locale sources (offline)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = json.loads((ROOT / "tool/locale_source.json").read_text(encoding="utf-8"))
RU: dict[str, str] = SRC["ru"]
TR: dict[str, str] = SRC.get("tr", {})

_OVERRIDES_PATH = ROOT / "tool/en_overrides.json"
FILE_OVERRIDES: dict[str, str] = (
    json.loads(_OVERRIDES_PATH.read_text(encoding="utf-8"))
    if _OVERRIDES_PATH.exists()
    else {}
)

# Keys that need explicit English (not derivable from TR/RU heuristics).
KEY_OVERRIDES: dict[str, str] = {
    "languageSelectTitle": "Choose language",
    "onboardingContinue": "Continue",
    "currency": "UZS",
    "madeInUzbekistan": "Made in Uzbekistan",
    "loginInfoSuffix": "",
    "policySuffix": "",
    "pcs": "pcs",
    "planPerMonth": "/mo",
    "planPerYear": "/yr",
    "daysLeftShort": "{n} days left",
    "billingMonthly": "Monthly",
    "billingYearly": "Yearly",
    "statusGraceLabel": "Grace period",
    "statusExpiredLabel": "Expired",
    "statusTrialing": "Trial period",
    "dashboardBatchUnitGeneric": "batch",
    "shopDeleteMessage": 'Delete "{name}"? This cannot be undone.',
    "appleSignInFailed": "Apple sign-in failed.",
    "googleSignInFailed": "Google sign-in failed.",
    "authErrorGoogleNoToken": "Google sign-in failed. Please try again.",
    "authErrorAppleNoToken": "Apple sign-in failed. Please try again.",
    "authErrorGoogleUnsupported": "Google sign-in is not supported on this device.",
    "aboutSupport": "Support",
    "sacks": "sacks",
    "sack": "Sack",
    "reportExpandProductsCount": "{n} items",
    "reportReturnsRecords": "rec.",
    "returnPieceSuffix": "pcs",
}

# Full RU sentence/fragment -> EN (covers all 711 keys via ru values).
RU_PHRASES: list[tuple[str, str]] = sorted(
    [
        ("Управляйте бизнесом одним взглядом", "Run your business at a glance"),
        ("Умная система для малого бизнеса", "Smart system for small business"),
        ("О приложении", "About the app"),
        (
            "TAQSEEM — приложение для точного расчёта себестоимости, прибыли и расходов малого и среднего производственного бизнеса.",
            "TAQSEEM is an app for accurately calculating cost, profit, and expenses for small and medium production businesses.",
        ),
        (
            "TAQSEEM — современная система управления для малого и среднего производственного бизнеса. Видите ежедневное производство, расходы, возвраты и чистую прибыль в одном месте, в реальном времени.",
            "TAQSEEM is a modern management system for small and medium production businesses. See daily production, expenses, returns, and net profit in one place, in real time.",
        ),
        ("Свяжитесь с нами", "Contact us"),
        ("Основные возможности", "Key features"),
        ("Telegram-канал", "Telegram channel"),
        ("Веб-сайт", "Website"),
        ("Почему TAQSEEM?", "Why TAQSEEM?"),
        ("Аккаунт", "Account"),
        ("Добавить", "Add"),
        ("Сохранить", "Save"),
        ("Добавить бизнес", "Add business"),
        ("Добавить сотрудника", "Add employee"),
        ("Название, единица и цена. Валюта — кнопка справа от суммы.", "Name, unit, and price. Choose currency with the button next to the amount."),
        ("Новое сырьё", "New ingredient"),
        ("Введите название и цену продажи", "Enter the name and selling price"),
        ("Новый тип", "New type"),
        ("Например: г. Ташкент, ул. Амира Темура, 1", "e.g. Tashkent, Amir Timur St., 1"),
        ("Нет подключения к интернету", "No internet connection"),
        ("Время ожидания истекло", "Connection timed out"),
        ("Неожиданная ошибка", "Unexpected error"),
        ("Неверный формат ответа", "Invalid response format"),
        ("Ошибка входа через Apple.", "Apple sign-in failed."),
        ("Ошибка входа через Google.", "Google sign-in failed."),
        ("Изображения (просмотр)", "Images (preview)"),
        ("Вернуться на главную", "Back to home"),
        ("Выпечено", "Produced"),
        ("Выпечено хлеба", "Bread produced"),
        ("Основной Баланс", "Main balance"),
        ("История баланса", "Balance history"),
        ("История пополнений и списаний", "Deposit and withdrawal history"),
        ("Типы продукции", "Product types"),
        ("Виды товаров или услуг — цена для каждой позиции", "Product or service types — set a price for each item"),
        ("Бизнес создан! 🎉", "Business created! 🎉"),
        ("{name} успешно создан.", "{name} was created successfully."),
        ("Краткое описание (необязательно)", "Short description (optional)"),
        ("Введите основные данные вашего бизнеса", "Enter your business details"),
        ("Сохраните GPS-координаты или введите адрес вручную", "Save GPS coordinates or enter the address manually"),
        ("Местоположение", "Location"),
        ("Название бизнеса", "Business name"),
        ("Например: Центральная пекарня", "e.g. Central Bakery"),
        ("Минимум 2 символа", "At least 2 characters"),
        ("Введите название бизнеса", "Enter a business name"),
        ("Владелец бизнеса", "Business owner"),
        ("Чистый итог", "Net result"),
        ("Внешний расход", "External expenses"),
        ("Изменить фото", "Change photo"),
        ("Распределение расходов", "Expense breakdown"),
        ("Производство", "Production"),
        ("Тренд прибыли", "Profit trend"),
        ("Распределение доходов", "Revenue breakdown"),
        ("Подробные графики", "Detailed charts"),
        ("Выбрать из галереи", "Choose from gallery"),
        ("Код не пришёл?", "Didn't receive the code?"),
        ("Подтвердите пароль", "Confirm password"),
        ("Скопировано", "Copied"),
        ("Копировать", "Copy"),
        ("Создать бизнес", "Create business"),
        ("Создайте свой первый бизнес\nи начните управление", "Create your first business\nand start managing"),
        ("создайте новый аккаунт", "create a new account"),
        ("Укажите тип бизнеса — мы это учтём", "Tell us your business type — we'll account for it"),
        ("Например: Выпечка, Лимонады...", "e.g. Bakery, Lemonades..."),
        ("После создания партии здесь появится сводка по продукции", "After you create a batch, a product summary will appear here"),
        ("Сегодня продукция не выпекалась", "No production today"),
        ("Расходы не записаны", "No expenses recorded"),
        ("Выпуск не записан", "No output recorded"),
        ("Выпуск за сегодня", "Today's output"),
        ("Внешние расходы", "External expenses"),
        ("Выпуск продукции", "Product output"),
        ("осталось {n} дн.", "{n} days left"),
        ("Пользователь", "User"),
        ("Удалить аккаунт", "Delete account"),
        ("Удалить навсегда", "Delete permanently"),
        ("Полное удаление вашего аккаунта", "Permanently delete your account"),
        ("Не удалось удалить аккаунт.", "Could not delete account."),
        ("Окончательное подтверждение", "Final confirmation"),
        (
            "Это последний шаг. После нажатия аккаунт и все ваши данные будут немедленно удалены.",
            "This is the last step. After you confirm, your account and all data will be deleted immediately.",
        ),
        ("Удаление аккаунта...", "Deleting account..."),
        ("Аккаунт успешно удалён.", "Account deleted successfully."),
        ("Удалить аккаунт?", "Delete account?"),
        (
            "При удалении аккаунта все ваши магазины, отчёты, рецепты и данные будут безвозвратно удалены. Действие нельзя отменить.",
            "If you delete your account, all your shops, reports, recipes, and data will be permanently removed. This cannot be undone.",
        ),
        ("Удалить расход", "Delete expense"),
        ("Удалить этот расход?", "Delete this expense?"),
        ("Разработчик", "Developer"),
        ("Последняя активность", "Last active"),
        ("Выйти", "Sign out"),
        ("Сессия этого устройства будет завершена.", "This device session will be ended."),
        (
            "Это текущее устройство. После выхода вы выйдете из системы.",
            "This is your current device. You will be signed out.",
        ),
        ("Не удалось отключить", "Could not sign out"),
        ("Выйти с устройства", "Sign out device"),
        ("Устройство отключено", "Device signed out"),
        ("Неизвестное устройство", "Unknown device"),
        ("Активные сессии появятся здесь", "Active sessions will appear here"),
        ("Нет устройств", "No devices"),
        ("Активные сессии", "Active sessions"),
        ("Устройства", "Devices"),
        ("Выключено", "Off"),
        ("Редактировать", "Edit"),
        ("Изменить email", "Change email"),
        ("Редактировать расход", "Edit expense"),
        ("Редактировать сырьё", "Edit ingredient"),
        ("Изменить имя", "Change name"),
        ("Редактировать тип", "Edit type"),
        ("Эл. почта", "Email"),
        ("Код подтверждения", "Verification code"),
        ("Подтвердить", "Confirm"),
        ("На номер {phone} отправлен 4-значный код", "A 4-digit code was sent to {phone}"),
        ("Подтвердите код", "Confirm code"),
        ("Сотрудник успешно добавлен", "Employee added successfully"),
        ("Бесплатных мест: осталось {n}", "Free seats remaining: {n}"),
        ("Пятничная скидка −{percent}%", "Friday discount −{percent}%"),
        ("Имя сотрудника", "Employee name"),
        ("Бесплатные места закончились", "No free seats left"),
        ("Платное место", "Paid seat"),
        (
            "Бесплатный лимит исчерпан. За этого сотрудника с баланса будет списано {price} (в месяц).",
            "Free limit reached. {price} per month will be charged from your balance for this employee.",
        ),
        ("Платное место сотрудника", "Paid employee seat"),
        ("За каждого нового сотрудника: {price}/мес", "For each new employee: {price}/mo"),
        (
            "Выберите, какими разделами может управлять сотрудник",
            "Choose which sections this employee can manage",
        ),
        ("Права сохранены", "Permissions saved"),
        ("Права доступа", "Access permissions"),
        (
            "Этот сотрудник не сможет войти в бизнес. Продолжить?",
            "This employee will no longer access the business. Continue?",
        ),
        ("Удалить сотрудника", "Remove employee"),
        ("Сотрудник удалён", "Employee removed"),
        ("Требуется оплата", "Payment required"),
        ("Продление: {date}", "Renews: {date}"),
        ("Добавьте первого сотрудника и настройте его права", "Add your first employee and set permissions"),
        ("Сотрудников пока нет", "No employees yet"),
        ("Сотрудники и их права", "Employees and permissions"),
        ("Сотрудники", "Employees"),
        ("Включено", "On"),
        ("Введите имя", "Enter name"),
        ("Введите пароль", "Enter password"),
        ("Введите телефон", "Enter phone number"),
        ("Новая категория", "New category"),
        ("Например: реклама", "e.g. advertising"),
        ("Сохранить категорию", "Save category"),
        ("Своя категория", "Custom category"),
        ("Ничего не найдено", "Nothing found"),
        ("Не удалось загрузить", "Could not load"),
        ("Поиск категорий", "Search categories"),
        ("Выберите тип и введите сумму.", "Select a type and enter the amount."),
        ("Добавить расход", "Add expense"),
        ("Ошибка удаления", "Delete failed"),
        ("Расход удалён", "Expense deleted"),
        ("Комментарий (необязательно)", "Comment (optional)"),
        ("Сохранить расход", "Save expense"),
        ("Ошибка обновления", "Update failed"),
        ("Расход обновлён", "Expense updated"),
        ("Внутренние расходы", "Internal expenses"),
        ("Удобные ночной и дневной режимы.", "Comfortable light and dark themes."),
        ("Тёмная / светлая тема", "Dark / light theme"),
        ("Отслеживайте все расходы по категориям.", "Track all expenses by category."),
        ("Управление расходами", "Expense management"),
        (
            "Приложение на 7 языках: узбекский, русский, казахский и др.",
            "7 languages: English, Uzbek, Russian, Kazakh, and more.",
        ),
        ("Мультиязычность", "Multilingual"),
        ("Управляйте несколькими точками из одного аккаунта.", "Manage multiple locations from one account."),
        ("Несколько точек", "Multiple locations"),
        ("Контроль ежедневного объёма и себестоимости.", "Daily production volume and cost control."),
        ("Учёт производства", "Production tracking"),
        ("Автоматический расчёт себестоимости ингредиентов.", "Calculate recipe and ingredient cost automatically."),
        ("Дневные, недельные и месячные графики и аналитика.", "Daily, weekly, and monthly charts and analytics."),
        ("Статистика и отчёты", "Statistics and reports"),
        ("Точный учёт возвратов и потерь.", "Accurate tracking of returns and losses."),
        ("Определение местоположения...", "Detecting location..."),
        ("Это поле обязательно", "This field is required"),
        ("Входите впервые? Сначала ", "First time here? First "),
        ("Расход муки", "Flour usage"),
        ("Имя и фамилия", "Full name"),
        ("Автоматически определить текущее местоположение", "Automatically detect current location"),
        ("Аккаунт будет заблокирован через {n} дн.", "Account will be blocked in {n} days"),
        ("Привет", "Hello"),
        ("Пока нет выпусков продукции", "No production entries yet"),
        ("Пока нет возвратов", "No returns yet"),
        ("Всего возвратов", "Total returns"),
        ("Главная", "Home"),
        ("Например: мука, вода, соль", "e.g. flour, water, salt"),
        (
            "Введите полную цену за выбранную единицу (например, за 1 кг, 1 л или 1 шт.). В рецепте можно использовать г или мл — здесь хранится общая цена.",
            "Enter the full price for the selected unit (e.g. per 1 kg, 1 L, or 1 pc). Recipes may use g or ml — the total price is stored here.",
        ),
        (
            "Введите общую цену сырья за единицу (1 кг, 1 шт. или 1 л). В рецептах система сама пересчитает в граммы или миллилитры.",
            "Enter the total ingredient price per unit (1 kg, 1 pc, or 1 L). Recipes automatically convert to grams or milliliters.",
        ),
        ("Цена за 1 единицу", "Price per 1 unit"),
        ("Цена за 1 {unit}", "Price per 1 {unit}"),
        ("Единица измерения", "Unit of measure"),
        ("Штука", "Piece"),
        ("Грамм (g)", "Gram (g)"),
        ("Килограмм (kg)", "Kilogram (kg)"),
        ("Литр (l)", "Liter (l)"),
        ("Ингредиенты", "Ingredients"),
        ("Добавить сырьё", "Add ingredient"),
        (
            "Укажите название, единицу измерения и цену за единицу для рецептов и себестоимости.",
            "Enter name, unit, and unit price for recipes and cost calculation.",
        ),
        ("Сырья пока нет", "No ingredients yet"),
        ("Пополните баланс для оплаты", "Top up your balance to pay"),
        ("Недостаточно средств", "Insufficient balance"),
        ("Неверный email", "Invalid email"),
        ("Лимит сотрудников достигнут. Перейдите на более высокий тариф.", "Employee limit reached. Upgrade your plan."),
        ("Лимит товаров достигнут. Перейдите на более высокий тариф.", "Product limit reached. Upgrade your plan."),
        ("Лимит бизнес-аккаунтов достигнут. Перейдите на более высокий тариф.", "Business account limit reached. Upgrade your plan."),
        ("Лимит достигнут", "Limit reached"),
        ("Привязать", "Link"),
        ("Привязан", "Linked"),
        ("Не удалось определить местоположение", "Could not detect location"),
        ("Местоположение необязательно. Можно добавить позже.", "Location is optional. You can add it later."),
        ("Доступ к местоположению запрещён. Откройте настройки.", "Location access denied. Open settings."),
        ("Местоположение сохранено", "Location saved"),
        ("Войти", "Sign in"),
        ("Создайте аккаунт", "Create an account"),
        ("Если у вас нет аккаунта, ", "If you don't have an account, "),
        ("Способы входа", "Sign-in methods"),
        ("Войдите для продолжения", "Sign in to continue"),
        ("Выйти из системы", "Sign out"),
        ("Вы хотите выйти из системы?", "Do you want to sign out?"),
        ("Выйти из аккаунта", "Sign out of account"),
        ("Убыток", "Loss"),
        ("Сделано в Узбекистане", "Made in Uzbekistan"),
        ("Управление и переключение", "Manage and switch"),
        ("Введите адрес вручную", "Enter address manually"),
        ("Имя обязательно", "Name is required"),
        ("Чистый доход", "Net income"),
        ("Выручка после возвратов", "Revenue after returns"),
        ("Нет аккаунта?", "Don't have an account?"),
        ("Нет активного тарифа", "No active plan"),
        ("Сегодня хлеб ещё не выпекался", "Nothing produced today yet"),
        ("Бизнесов пока нет", "No businesses yet"),
        ("Сегодня расходов нет", "No expenses today"),
        ("Ошибка подключения к интернету", "Internet connection error"),
        ("Нет заказов", "No orders"),
        ("История ваших покупок появится здесь", "Your purchase history will appear here"),
        ("Нет транзакций", "No transactions"),
        ("Движения по балансу появятся здесь", "Balance activity will appear here"),
        ("Не привязан", "Not linked"),
        (
            "Пекарня, шашлычная, самсахана, кондитерская, фастфуд — управляйте из одного места",
            "Bakery, grill, samsa shop, confectionery, fast food — manage everything in one place",
        ),
        (
            "Точно рассчитайте себестоимость каждого продукта и узнайте реальную прибыль",
            "Calculate each product's cost accurately and know your real profit",
        ),
        (
            "Отслеживайте продажи, расходы и производство в реальном времени",
            "Track sales, expenses, and production in real time",
        ),
        ("Для любого бизнеса", "For any business"),
        ("Себестоимость и прибыль", "Cost and profit"),
        ("Бизнес под контролем", "Business under control"),
        ("или введите вручную", "or enter manually"),
        ("Раздел заказов находится в разработке.\nСкоро будет готов!", "The orders section is under development.\nIt will be ready soon!"),
        ("4-значный код подтверждения\nотправлен на {phone}.", "A 4-digit verification code\nwas sent to {phone}."),
        ("Введите код", "Enter code"),
        ("Пароли не совпадают", "Passwords do not match"),
        ("Срок подписки истёк", "Subscription expired"),
        ("Купите тариф, чтобы продолжить", "Purchase a plan to continue"),
        ("Подберите подходящий план для вашего бизнеса", "Pick the plan that fits your business"),
        ("Выберите тариф", "Choose a plan"),
        ("Продукты", "Products"),
        ("Рецепты", "Recipes"),
        ("Продажи / Возврат", "Sales / Returns"),
        ("Личные данные", "Personal info"),
        (
            "Номер {phone} уже зарегистрирован.\n\nВойдите с этим номером.",
            "Number {phone} is already registered.\n\nSign in with this number.",
        ),
        ("Номер уже зарегистрирован", "Number already registered"),
        ("Номер телефона", "Phone number"),
        ("Фото удалено", "Photo removed"),
        ("Фото обновлено", "Photo updated"),
        ("Не удалось загрузить фото", "Could not upload photo"),
        ("{n} сотрудник(ов)", "{n} employees"),
        ("Без сотрудников", "No employees"),
        ("Безлимит сотрудников", "Unlimited employees"),
        ("{n} товаров", "{n} products"),
        ("Безлимит товаров", "Unlimited products"),
        ("{n} бизнес-аккаунт", "{n} business accounts"),
        ("Безлимит бизнес-аккаунтов", "Unlimited business accounts"),
        ("Популярный", "Most popular"),
        ("/мес", "/mo"),
        ("/год", "/yr"),
        ("Выгода", "You save"),
        (" и ", " and "),
        ("Входя, вы принимаете ", "By signing in, you accept the "),
        ("Конфиденциальность", "Privacy"),
        ("Регистрируясь, вы принимаете ", "By registering, you accept the "),
        ("Условия", "Terms"),
        ("Нажмите ещё раз, чтобы выйти", "Press back again to exit"),
        ("Политика конфиденциальности", "Privacy policy"),
        ("Защита персональных данных", "Personal data protection"),
        ("Добавить тип", "Add type"),
        ("Добавьте виды товаров или услуг, которые продаёте", "Add the product or service types you sell"),
        ("Пока нет типов продукции", "No product types yet"),
        ("Например: лаваш, сет-меню", "e.g. lavash, set menu"),
        ("ПАРТИИ", "BATCHES"),
        ("Валовая сумма", "Gross amount"),
        ("Чистая выручка", "Net revenue"),
        ("Чистое количество", "Net quantity"),
        ("Всего выпущено", "Total produced"),
        ("Возвращённое количество", "Returned quantity"),
        ("Возврат:", "Returned:"),
        ("Сумма возврата", "Return amount"),
        ("Продукция выпущена", "Products produced"),
        ("Возврат продукции", "Product return"),
        ("Цена продажи за 1 {unit}", "Selling price per 1 {unit}"),
        ("Количество партий", "Batch count"),
        ("Партия обновлена", "Batch updated"),
        ("По ингредиентам", "By ingredients"),
        (
            "Запись о выпуске будет удалена. Если по этому типу за дату не останется других партий, все возвраты за этот тип тоже удалятся.",
            "The production entry will be deleted. If no other batches remain for this type on this date, all returns for this type will also be deleted.",
        ),
        ("Удалить выпуск?", "Delete production?"),
        ("Запись будет удалена. Главная и суммы обновятся.", "The entry will be deleted. Home totals will refresh."),
        ("Удалить возврат?", "Delete return?"),
        ("Количество партий сегодня", "Batch count today"),
        ("За сегодня возвратов по этому типу нет", "No returns for this type today"),
        ("Возвраты по этому типу (сегодня)", "Returns for this type (today)"),
        ("Сохранить партию", "Save batch"),
        ("Партия и возвраты", "Batch and returns"),
        ("{g} г", "{g} g"),
        ("Себестоимость сырья", "Ingredient cost"),
        ("Ингредиенты рецепта отсутствуют или не загрузились.", "Recipe ingredients are missing or failed to load."),
        ("1 партия (рецепт)", "1 batch (recipe)"),
        ("Цена за единицу", "Price per unit"),
        ("Выпуск удалён", "Production deleted"),
        ("Итого количество", "Total quantity"),
        ("Возврат удалён", "Return deleted"),
        ("Возврат за сегодня (по этому типу)", "Today's return (this type)"),
        ("Ориентировочная выручка", "Estimated revenue"),
        ("Закрытая сегодня партия", "Batch closed today"),
        ("Партия подробно", "Batch details"),
        ("Количество ({unit})", "Quantity ({unit})"),
        ("Затраты", "Cost"),
        ("Записать выпуск", "Record production"),
        ("Расход сырья", "Ingredient usage"),
        (
            "Для этого типа нет рецепта. Сначала создайте расчёт в разделе «Система расчёта».",
            "No recipe for this type. First create a calculation in the “Costing system” section.",
        ),
        ("Поиск продукции", "Search products"),
        ("Выберите тип, привязанный к расчёту (рецепту).", "Select a type linked to a calculation (recipe)."),
        ("Какая продукция?", "Which product?"),
        ("1 {unit} = {qty} {productUnit}. Допускаются дроби (например: 1.5).", "1 {unit} = {qty} {productUnit}. Decimals allowed (e.g. 1.5)."),
        ("Количество партий", "Batch quantity"),
        ("Проверьте данные и сохраните.", "Review the data and save."),
        ("Проверка и сохранение", "Review and save"),
        ("Выпуск {qty} {unit} записан", "Recorded production of {qty} {unit}"),
        ("Расчёт", "Calculation"),
        ("Введите количество партий больше 0", "Enter a batch quantity greater than 0"),
        ("Для этого типа нет рецепта", "No recipe for this type"),
        ("Выберите тип продукции", "Select a product type"),
        ("Мука, вода, соль, дрожжи, масло...", "Flour, water, salt, yeast, oil..."),
        ("Данные профиля", "Profile info"),
        ("Телефон, почта и настройки Telegram", "Phone, email, and Telegram settings"),
        ("Данные обновлены", "Profile updated"),
        ("Тариф {plan} будет приобретён за {price}. Продолжить?", "Purchase {plan} plan for {price}. Continue?"),
        ("Подтвердите покупку", "Confirm purchase"),
        ("Тариф активирован", "Plan activated"),
        ("Нельзя изменить", "Read-only"),
        ("Загрузите фото чека", "Upload a receipt photo"),
        ("Добавить рецепт", "Add recipe"),
        ("Добавить позицию", "Add item"),
        ("Рецепт уже создан", "Recipe already exists"),
        ("Как считаете на производстве: мешок, блок, комплект...", "How you count in production: sack, block, set..."),
        ("Единица партии", "Batch unit"),
        ("{name} · {qty} {unit}", "{name} · {qty} {unit}"),
        ("Себестоимость партии", "Batch cost"),
        ("Себестоимость 1 шт", "Unit cost"),
        ("Себестоимость сырья на одну партию (всего).", "Total ingredient cost for one batch."),
        ("Количество продукции за одну партию.", "Product quantity per batch."),
        ("Себестоимость единицы продукции (всего ÷ выпуск).", "Unit product cost (total ÷ output)."),
        ("Создать новое сырьё", "Create new ingredient"),
        ("Если его нет в списке — добавьте прямо отсюда", "If it's not in the list, add it here"),
        ("Новый рецепт", "New recipe"),
        ("Рецепт «{name}» будет удалён. Это действие нельзя отменить.", "Recipe “{name}” will be deleted. This cannot be undone."),
        ("Удалить рецепт?", "Delete recipe?"),
        ("Рецепт удалён", "Recipe deleted"),
        ("Добавьте рецепты для типов продукции — учёт производства будет точным.", "Add recipes for product types for accurate production tracking."),
        ("Рецептов пока нет", "No recipes yet"),
        ("Произошла ошибка", "Something went wrong"),
        ("Введите количества на одну партию в выбранной единице.", "Enter quantities for one batch in the selected unit."),
        ("Укажите, сколько каждого сырья идёт на 1 {unit}.", "Enter how much of each ingredient goes into 1 {unit}."),
        ("Количество сырья на одну партию", "Ingredient quantity per batch"),
        ("Количество сырья на 1 {unit}", "Ingredient quantity per 1 {unit}"),
        ("Например: 100", "e.g. 100"),
        ("Количество продукции", "Product quantity"),
        ("Сколько продукции с 1 {unit}?", "How much product from 1 {unit}?"),
        ("Сколько единиц продукции получается из 1 партии?", "How many product units come from 1 batch?"),
        ("1 {unit} → {qty} шт", "1 {unit} → {qty} pcs"),
        ("Рецепт сохранён", "Recipe saved"),
        ("Выберите один тип — для каждого типа один рецепт.", "Select one type — one recipe per type."),
        ("Для какого продукта?", "For which product?"),
        ("Один и тот же ингредиент добавлен дважды", "The same ingredient was added twice"),
        ("Добавьте хотя бы одно сырьё", "Add at least one ingredient"),
        ("Введите количество выпуска", "Enter output quantity"),
        ("Состав и количество для хлеба", "Composition and quantities for bread"),
        ("Зарегистрируйтесь", "Register"),
        ("Введите все данные", "Enter all details"),
        ("Регистрация", "Registration"),
        ("Удалить фото", "Remove photo"),
        ("Удалить фото профиля?", "Remove profile photo?"),
        ("Нет данных по продуктам", "No product data"),
        ("Нет возвратов за период", "No returns in this period"),
        ("{n} поз.", "{n} items"),
        ("{n} типов", "{n} types"),
        ("Выручка до возвратов", "Gross revenue"),
        ("Записей выпуска", "Production records"),
        ("30 дней", "30 days"),
        ("7 дней", "7 days"),
        ("зап.", "rec."),
        ("По продуктам", "By product"),
        ("Возвраты по типу", "Returns by type"),
        ("Отправить код повторно", "Resend code"),
        ("Повторная отправка: {time}", "Resend in: {time}"),
        (
            "Укажите тип и количество возврата. При выборе типа цена продажи подставится автоматически.",
            "Enter return type and quantity. Selling price fills in automatically when you select a type.",
        ),
        ("Возврат продукции", "Product return"),
        ("Записать возврат", "Record return"),
        (
            "За сегодня нет выпуска по этому типу. Сначала запишите выпуск.",
            "No production for this type today. Record production first.",
        ),
        ("Цена за штуку", "Price per piece"),
        ("Партия (выпуск)", "Batch (production)"),
        (
            "После записи возврата обновятся дневные продажи, выручка и прибыль (главная и отчёты) — так отражается реальная картина.",
            "After recording a return, daily sales, revenue, and profit update on home and reports — reflecting the real picture.",
        ),
        ("Учёт возврата важен для корректной прибыли.", "Return tracking is important for accurate profit."),
        ("Прибыль и учёт", "Profit and accounting"),
        ("Введите целое число (шт.).", "Enter a whole number (pcs)."),
        ("Количество возврата", "Return quantity"),
        ("Например: клиент, качество", "e.g. customer, quality"),
        ("Причина (необязательно)", "Reason (optional)"),
        ("Возврат записан", "Return recorded"),
        ("Введите корректную цену", "Enter a valid price"),
        ("Количество должно быть больше 0", "Quantity must be greater than 0"),
        ("Продажи и возвраты", "Sales and returns"),
        ("Выберите бизнес, которым хотите управлять", "Choose the business you want to manage"),
        ("Выберите тип бизнеса", "Select business type"),
        ("Выберите подходящую категорию — интерфейс адаптируется", "Choose a category — the interface adapts"),
        ("Валюта для отчётов и цен", "Currency for reports and prices"),
        ("Цена продажи", "Selling price"),
        ("Готово", "Done"),
        ("Сырьё и ингредиенты", "Ingredients"),
        ("Система расчёта", "Costing system"),
        ("Типы вашей продукции", "Your product types"),
        ("Мука, вода, соль, дрожжи, масло — цена и единица для каждого.", "Flour, water, salt, yeast, oil — price and unit for each."),
        ("Введите ингредиенты и сырьё с ценами и единицами измерения.", "Enter ingredients with prices and units of measure."),
        ("Мясо, специи, масло — цена и единица для каждого.", "Meat, spices, oil — price and unit for each."),
        ("Продукты и ингредиенты — связь со складом и себестоимостью.", "Products and ingredients linked to inventory and cost."),
        ("Соотношение ингредиентов и себестоимость — прибыль понятна.", "Ingredient ratios and cost — profit is clear."),
        ("Рецепты и себестоимость — маржа и прибыль по каждому товару.", "Recipes and cost — margin and profit per item."),
        ("Граммы и себестоимость на блюдо — цена и прибыль.", "Grams and cost per dish — price and profit."),
        ("Себестоимость блюд и напитков — отчёты автоматически.", "Food and drink cost — reports update automatically."),
        ("Например: патир, самса, лаваш, тандыр... Отдельная цена для каждого вида.", "e.g. patir, samsa, lavash, tandoor... Separate price for each type."),
        ("Добавляйте категории продукции и услуг, управляйте ценами.", "Add product and service categories and manage prices."),
        ("Например: шашлык, люля, рулет... Отдельная цена за каждую позицию.", "e.g. kebab, lyulya, roll... Separate price for each item."),
        ("Например: блюда, гарниры, напитки... Структурируйте по меню.", "e.g. dishes, sides, drinks... Structure by menu."),
        ("Все шаги выполнены", "All steps completed"),
        (
            "Сначала создайте тип продукции, затем добавьте сырьё и цены, затем настройте расчёт по рецепту — так приложение посчитает себестоимость и прибыль.",
            "First create a product type, then add ingredients and prices, then set up recipe costing — the app will calculate cost and profit.",
        ),
        ("Порядок настройки", "Setup order"),
        ("Например: Ташкент, Чиланзар", "e.g. Tashkent, Chilonzor"),
        ("Удалить бизнес «{name}»? Это действие нельзя отменить.", 'Delete business "{name}"? This cannot be undone.'),
        ("Бизнес удалён", "Business deleted"),
        ("Например: Моя пекарня", "e.g. My Bakery"),
        ("Настройки бизнеса", "Business settings"),
        ("Бизнес обновлён", "Business updated"),
        ("Войти с Apple", "Sign in with Apple"),
        ("Войти через Google", "Sign in with Google"),
        (
            "Если у вас нет баланса на Uzmobile, SIM-карта может не принимать SMS.",
            "If your Uzmobile balance is empty, the SIM may not receive SMS.",
        ),
        ("Баланс Uzmobile", "Uzmobile balance"),
        ("Частые причины:", "Common reasons:"),
        ("SMS код не пришёл?", "SMS code not received?"),
        ("Проверьте папку «Спам» в SMS. Наш SMS отправлен с номера 4546.", "Check the Spam folder in SMS. Our SMS is sent from 4546."),
        ("{name} добавлено", "{name} added"),
        ("{name} удалено", "{name} deleted"),
        ("{name} обновлено", "{name} updated"),
        ("Заполните все поля", "Fill in all fields"),
        ("Наши соцсети", "Our social channels"),
        ("Новости и анонсы", "News and announcements"),
        ("Вход через {name} скоро появится", "Sign in with {name} coming soon"),
        ("Продано (авто)", "Sold (auto)"),
        ("Управление персоналом", "Staff management"),
        ("Начать работу", "Start working"),
        (
            "Введите тип производимого продукта",
            "Enter the type of product you produce",
        ),
        ("Добавьте продукт", "Add product"),
        ("Введите ингредиенты для рецепта", "Enter ingredients for the recipe"),
        ("Добавьте сырьё", "Add ingredients"),
        ("Укажите количество сырья на 1 продукт", "Enter ingredient quantity per 1 product"),
        ("Создайте расчёт", "Create costing"),
        ("Введите сколько продуктов выпущено сегодня", "Enter how many products were produced today"),
        ("Запишите расход", "Record usage"),
        ("Нажмите кнопку добавить", "Tap the add button"),
        ("Корректировка", "Adjustment"),
        ("Место сотрудника", "Employee seat"),
        ("Оплата подписки", "Subscription payment"),
        ("Повторить", "Try again"),
        ("Загрузить фото чека", "Upload receipt photo"),
        ("Загрузка...", "Uploading..."),
        ("Определить по GPS", "Detect via GPS"),
        ("Действует до", "Valid until"),
        ("Смотреть тарифы", "View plans"),
        ("Кошелёк", "Wallet"),
        ("Добро пожаловать!", "Welcome back!"),
        ("Годовые подписки недоступны", "Yearly subscriptions unavailable"),
        ("Годовые тарифы пока не добавлены.", "Yearly plans are not available yet."),
        ("Пробный период", "Free trial"),
        ("Осталось {n} дн. пробного периода", "{n} days left in trial"),
        ("Пробный период заканчивается", "Trial ending soon"),
        ("Перейти", "Go"),
        ("Нажмите кнопку настройки", "Tap the setup button"),
        ("Настройте продукты, сырьё и расчёты", "Set up products, ingredients, and costing"),
        ("Нажмите на эту карточку, чтобы войти в настройки", "Tap this card to open settings"),
        ("Откройте раздел", "Open section"),
        ("Запишите сегодняшний выпуск продукции через эту кнопку", "Record today's production output with this button"),
        ("Приход продукта", "Product intake"),
        (
            "Добавьте продукты и сырьё — приложение само посчитает себестоимость и прибыль.",
            "Add products and ingredients — the app calculates cost and profit automatically.",
        ),
        ("Сначала настройте", "Set up first"),
        ("Подключение...", "Connecting..."),
        ("Открываем Telegram", "Opening Telegram"),
        ("Открыть Telegram снова", "Open Telegram again"),
        ("Попробовать снова", "Try again"),
        ("Время истекло. Попробуйте снова.", "Time expired. Please try again."),
        (
            "Отправьте номер телефона в Telegram и нажмите кнопку возврата в приложение",
            "Send your phone number in Telegram and tap return to the app",
        ),
        ("Ожидание Telegram", "Waiting for Telegram"),
        ("Условия использования", "Terms of service"),
        ("Правила оказания услуг", "Service terms"),
        (
            "Возможно, этот аккаунт Telegram уже привязан к другому пользователю. Попробуйте снова.",
            "This Telegram account may already be linked to another user. Try again.",
        ),
        ("Не удалось подключить", "Could not connect"),
        ("Открыть Telegram", "Open Telegram"),
        ("Откроется Telegram и наш бот", "Telegram and our bot will open"),
        ("Нажмите «Start» в Telegram", "Tap Start in Telegram"),
        ("Ваш аккаунт подключится автоматически", "Your account will connect automatically"),
        ("Подключите аккаунт, чтобы получать уведомления через Telegram", "Link your account to receive notifications via Telegram"),
        ("Теперь вы будете получать важные уведомления в Telegram.", "You will now receive important notifications in Telegram."),
        ("Telegram подключён!", "Telegram connected!"),
        ("Подключить Telegram", "Connect Telegram"),
        (
            "Нажмите «Start» в Telegram. После подключения вы вернётесь автоматически.",
            "Tap Start in Telegram. After linking, you'll return automatically.",
        ),
        ("Подтвердите в Telegram", "Confirm in Telegram"),
        ("Убыток за сегодня", "Today's loss"),
        ("Прибыль за сегодня", "Today's profit"),
        ("Минимальная сумма — 1 000 сум", "Minimum amount is 1,000 UZS"),
        ("Номер карты", "Card number"),
        ("Владелец карты", "Cardholder name"),
        (
            "Раздел пополнения баланса находится в разработке. Скоро вы сможете полноценно пользоваться приложением.",
            "Balance top-up is under development. You'll be able to use the app fully soon.",
        ),
        ("Скоро будет доступно", "Coming soon"),
        ("Пополнение подтверждается администратором", "Top-ups are approved by admin"),
        ("Как пополнить?", "How to top up?"),
        ("Пополнить баланс", "Top up balance"),
        ("Запрос принят. Баланс обновится после подтверждения.", "Request received. Balance updates after approval."),
        ("Запрос на пополнение", "Top-up request"),
        ("Всего произведено", "Total produced"),
        ("Сделать фото", "Take photo"),
        ("Нажмите на карту, чтобы выбрать местоположение", "Tap the map to select a location"),
        ("Вернуться к входу", "Back to sign in"),
        ("Техническая поддержка", "Technical support"),
        ("Свяжитесь с нами через Telegram", "Contact us via Telegram"),
        ("Войти\nв приложение", "Enter\n the app"),
        ("Подтверждение", "Verification"),
        ("Льготный период", "Grace period"),
        ("В ожидании", "Pending"),
        ("Оплачено", "Paid"),
        ("Отменено", "Cancelled"),
        ("Возвращено", "Returned"),
        ("мешк.", "sacks"),
        ("парт.", "batch"),
        ("шт.", "pcs"),
        ("шт", "pcs"),
        ("сум", "UZS"),
        ("Instagram", "Instagram"),
        ("Telegram", "Telegram"),
        ("0", "0"),
    ],
    key=lambda x: -len(x[0]),
)


def has_cyrillic(text: str) -> bool:
    return bool(re.search(r"[\u0400-\u04FF]", text))


def translate_ru(text: str) -> str:
    if not text.strip():
        return text
    out = text
    for src, dst in RU_PHRASES:
        out = out.replace(src, dst)
    return out


def translate_key(key: str) -> str:
    if key in FILE_OVERRIDES:
        return FILE_OVERRIDES[key]
    if key in KEY_OVERRIDES:
        return KEY_OVERRIDES[key]
    ru_val = RU.get(key, "")
    tr_val = TR.get(key, "")
    if tr_val and not has_cyrillic(tr_val):
        # Turkish latin text: prefer RU phrase map on ru value for quality.
        en = translate_ru(ru_val)
    else:
        en = translate_ru(ru_val)
    if has_cyrillic(en):
        # Fallback: title-case key
        en = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", key)
        en = en.replace("_", " ").replace("  ", " ").strip().capitalize()
    return en.strip()


def dart_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def main() -> None:
    keys = sorted(RU.keys())
    en = {k: translate_key(k) for k in keys}

    out_path = ROOT / "lib/core/l10n/translations_en.dart"
    lines = [
        "// Generated by tool/build_en_dart.py — do not edit by hand.",
        "// Re-generate after adding localization keys to translations.dart.",
        "",
        "const Map<String, String> kEnTranslations = {",
    ]
    for key in keys:
        lines.append(f"  '{key}': '{dart_escape(en[key])}',")
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")

    cyr = [k for k in keys if has_cyrillic(en[k])]
    blank = [k for k in keys if not en[k].strip() and k not in ("loginInfoSuffix", "policySuffix")]
    print(f"Wrote {out_path} ({len(keys)} keys)")
    print(f"Cyrillic remaining: {len(cyr)}")
    print(f"Blank (unexpected): {blank}")
    if cyr[:5]:
        print("Cyrillic sample:", [(k, en[k][:60]) for k in cyr[:5]])


if __name__ == "__main__":
    main()
